apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\luca.milan\.kind\kompose.exe convert -f docker-compose-apps.yml -o .\Kubernetes\Kompose
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\luca.milan\.kind\kompose.exe convert -f docker-compose-apps.yml -o .\Kubernetes\Kompose
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/network: "true"
        io.kompose.service: grafana
    spec:
      containers:
        - image: guardian/grafana:0.0.1-SNAPSHOT
          name: monitoring-grafana
          ports:
            - containerPort: 3000
          resources: {}
      hostname: grafana
      restartPolicy: Always
status: {}
