apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\luca.milan\.kind\kompose.exe convert -f docker-compose-apps.yml -o .\Kubernetes\Kompose
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: micro-api-alarm
  name: micro-api-alarm
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    io.kompose.service: micro-api-alarm
status:
  loadBalancer: {}
