apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    orgId: 1
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    basicAuth: false
    version: 1
    editable: false
